version: 0.0

os: linux

file_exists_behavior: OVERWRITE

files:
  - source: docker-compose.prod.yml
    destination: /home/ubuntu

  - source: nginx.conf
    destination: /home/ubuntu

hooks:
  ApplicationStart:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ubuntu
      