# Es el docker compose de desarrollo
services:
  api:
    build: .
    container_name: cityexpress_api
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./newrelic.ini:/app/newrelic.ini:ro
    # Reescribe el CMD del dockerfile para desarrollo
    command: sh -c "python3 -c 'from src.database import engine, Base; from src.models import Package, CityConnection, PackageEvent, ShipmentRequest, Payment, RoutingJob; Base.metadata.create_all(bind=engine)' && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - NEW_RELIC_CONFIG_FILE=/app/newrelic.ini
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NEW_RELIC_APP_NAME=CityExpress-API-Dev
    # agregue esto pq la API arranca antes q la DB esté lista
    depends_on:
      db:
        condition: service_healthy
    restart: always

  consumer:
    build: .
    container_name: cityexpress_consumer
    command: python -m src.rabbitmq.consumer
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
    depends_on:
      db:
        condition: service_healthy
    restart: always

  newrelic-infra:
    image: newrelic/infrastructure:latest
    container_name: newrelic-infra
    cap_add:
      - SYS_PTRACE
    network_mode: host
    pid: host
    privileged: true
    environment:
      - NRIA_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - TINI_SUBREAPER=1
    volumes:
      - "/:/host:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/etc/os-release:/host/etc/os-release:ro"
    restart: unless-stopped
    user: root

  db:
    image: postgres:15-alpine
    container_name: cityexpress_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # healthcheck para asegurarse de que la base de datos esté lista antes de que la API intente conectarse
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: