# Es el docker compose de produccion, usa la imagen de ECR
services:
  api:
    # Es el URI del ECR
    image: ${API_IMAGE_URI}:latest
    container_name: cityexpress_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
      - NEW_RELIC_CONFIG_FILE=/app/newrelic.ini
      - NEW_RELIC_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
      - NEW_RELIC_APP_NAME=CityExpress-API-Prod
    # agregue esto pq la API arranca antes q la DB esté lista
    depends_on:
      db:
        condition: service_healthy
    restart: always

  consumer:
    image: ${API_IMAGE_URI}:latest
    container_name: cityexpress_consumer
    command: python -m src.rabbitmq.consumer
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - AUTH0_DOMAIN=${AUTH0_DOMAIN}
      - AUTH0_AUDIENCE=${AUTH0_AUDIENCE}
    depends_on:
      db:
        condition: service_healthy
    restart: always

  newrelic-infra:
    image: newrelic/infrastructure:latest
    container_name: newrelic-infra
    cap_add:
      - SYS_PTRACE
    network_mode: host
    pid: host
    privileged: true
    environment:
      - NRIA_LICENSE_KEY=${NEW_RELIC_LICENSE_KEY}
    volumes:
      - "/:/host:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped
    user: root

  db:
    image: postgres:15-alpine
    container_name: cityexpress_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # healthcheck para asegurarse de que la base de datos esté lista antes de que la API intente conectarse
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: